format = """
[ ](bg:dark-grey)\
[ \uf179 ](bg:dark-grey fg:bold white)\
[\ueb70 ](fg:dark-grey bg:light-green)\
$directory\
[\ueb70 ](fg:light-green bg:dark-magenta)\
$git_branch\ 
$git_status\
[\ueb70 ](fg:dark-magenta bg:light-blue)\
$docker_context\
[\ueb70 ](fg:light-blue bg:light-yellow)\
$python\
[\ueb70 ](fg:light-yellow bg:red)\
$nodejs\
[\ueb70 ](fg:red)\
$lua\
$golang\
$time 
$character
"""
palette = 'nightfox'

[character]
success_symbol = '[﬌](fg:bold light-green)'
error_symbol = '[﬌](fg:bold red)'

[directory]
read_only = " "
style = "bg:light-green fg:bold black"
format = "[ \uf115 $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[docker_context]
symbol = " "
style = 'bg:light-blue fg:bold dark-blue'
format = '[$symbol$context ]($style)'

[git_branch]
style = 'bg:dark-magenta fg:bold white'
symbol = " "
format = '[$symbol$branch(:$remote_branch) ]($style)'

[git_status]
style = 'bg:dark-magenta'
format = '([\[$all_status$ahead_behind\] ]($style))'

[golang]
symbol = " "

[lua]
symbol = " "

[nodejs]
style = 'bg:red fg:bold white'
format = '[$symbol($version )]($style)'
symbol = " "

[python]
symbol = " "
format = '[via ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\)) ]($style)'
style='bg:light-yellow fg:black'

[rust]
symbol = " "

## Custom palettes
[palettes.nightfox]
dark-grey = '#222222'
dark-blue = '#29394f'
light-blue = '#719cd6'
light-green = '#81b29a'
red = '#c94f6d'
black = '#000000'
light-magenta = '#cdbbea'
magenta = '#9d79d6'
dark-magenta = '#4a2881'
white = '#ffffff'
light-yellow = '#e0d81f'
