format = """
[ \uf179 ](bg:dark-grey fg:bold white)\
[\ueb70 ](fg:dark-grey)\
$directory\
$git_branch\ 
$git_status\
$docker_context\
$python\
$nodejs\
$golang\
$lua\
$time 
$character
"""
# format = """
# [ ](bg:dark-grey)\
# [ \uf179 ](fg:bold white)\
# [\ueb70 ](fg:dark-grey bg:light-green)\
# $directory\
# [\ueb70 ](fg:light-green bg:dark-magenta)\
# $git_branch\ 
# $git_status\
# [\ueb70 ](fg:dark-magenta bg:light-blue)\
# $docker_context\
# [\ueb70 ](fg:light-blue bg:light-yellow)\
# $python\
# [\ueb70 ](fg:light-yellow bg:red)\
# $nodejs\
# [\ueb70 ](fg:red bg:dark-grey)\
# $golang\
# [\ueb70 ](fg:dark-grey)\
# $lua\
# $time 
# $character
# """
palette = 'nightfox'

[character]
success_symbol = '[﬌](fg:bold light-green)'
error_symbol = '[﬌](fg:bold red)'

[directory]
read_only = " "
style = "fg:bold white"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[docker_context]
symbol = " "
style = 'fg:bold dark-blue'
format = '[$symbol$context ]($style)'

[git_branch]
style = 'fg:bold light-blue'
symbol = " "
format = '[$symbol$branch(:$remote_branch) ]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'

[golang]
style = "fg:bold light-green"
symbol = " "
format = '[$symbol($version) ]($style)'

[lua]
style = 'fg:bold light-grey'
symbol = " "
format = '[$symbol($version )]($style)'

[nodejs]
style = 'fg:bold white'
format = '[$symbol($version )]($style)'
symbol = " "

[python]
symbol = " "
format = '[via ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\)) ]($style)'
style='fg:light-yellow'

[rust]
symbol = " "

## Custom palettes
[palettes.nightfox]
dark-grey = '#333333'
dark-blue = '#29394f'
light-blue = '#719cd6'
light-green = '#81b29a'
red = '#c94f6d'
black = '#000000'
light-magenta = '#cdbbea'
magenta = '#9d79d6'
dark-magenta = '#4a2881'
white = '#ffffff'
light-yellow = '#e0d81f'
light-grey = '#CCCCCC'
